#!/bin/sh
_=[[
mkdir -p target
IFS=:
for D in ${PATH}; do
  for F in "${D}"/lua "${D}"/lua5* "${D}"/luajit*; do
    if [ -x "${F}" ]; then
      exec "${F}" ".carl/carl.lua" "$@"
    fi
  done
done
printf "%s: no Lua interpreter found\n" "${0##*/}" >&2
exit 1
]]
